config/routes.rb
Rails.application.routes.draw do
  get 'backend', to: 'backend#index'

  devise_for :users

  root 'main#index'
  get '/work_experience', to: 'main#work_experience'
  get '/education', to: 'main#education'
  get '/articles', to: 'main#articles'
  get 'hobbies', to: 'main#hobbies'
  get '/other_skills', to: 'main#other_skills'
  get '/talks_seminars', to: 'main#talks_seminars'
  get '/additional_training', to: 'main#additional_training'
  get '/additional_training/teaching', to: 'main#teaching'
  get '/blogs/griechischekueche', to: 'main#griechischekueche'
  get '/blogs/lowcarbdeutschland', to: 'main#lowcarbdeutschland'
  get '/blogs/engamovios', to: 'main#engamovios'
  get '/educationwork', to: 'main#educationwork'
  get '/jobsforastronomers', to: 'main#jobsforastronomers'
  get '/impressum', to: 'main#impressum'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backend_controller.rb
class BackendController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def index
  end   
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backend_helper.rb
module BackendHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/backend/index.html.erb
<h1>Backend#index</h1>
<p>Find me in app/views/backend/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 	 <title>Dr. Ioanna Arka</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><%= link_to "About", root_path%> <span class="sr-only">(current)</span></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Short Bio <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="<%=education_path%>"> Education </a></li>
            <li><a href="<%=work_experience_path%>"> Work Experience </a></li>
            <li><a href="<%=other_skills_path%>"> Other Skills </a></li>
            <li class="divider"></li>
            <li><a href="<%=additional_training_path%>"> Additional Training </a></li>
            <li><a href="<%=hobbies_path%>"> Hobbies/Interests </a></li>
          </ul>
        </li>
	        <li><%= link_to "Jobs for Astronomers", jobsforastronomers_path%></a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Μy blogs <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><a href="<%=blogs_griechischekueche_path%>"> <i class="famfamfam-flag-de"></i> Griechische Küche </a></li>
	            <li><a href="<%=blogs_lowcarbdeutschland_path%>"> <i class="famfamfam-flag-de"></i> Low Carb Deutschland </a></li>
	            <li class="divider"></li>
	            <li><a href="<%=blogs_engamovios_path%>">  <i class="famfamfam-flag-gr"></i>	 Εν Γάμω Βίος</a></li>
	          </ul>
	        </li>
	      </ul>
	      <a class="navbar-brand navbar-right"> Ioanna Arka </a>
	    </div><!-- /.navbar-collapse -->
			
     
	  </div><!-- /.container-fluid -->
	</nav>

<%= notice %>
<%= alert %>

<%= yield %>

<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
   		 <ul class="nav navbar-nav">
   		 	<li><%= link_to "Impressum / Contact", impressum_path %></li>
   		 </ul>
  	</div>
	</div>
</nav>

</body>
	
</html>

app/views/main/additional_training.html.erb
<div class='box-i'>
	<div class='short'>
  <h4> Additional Training (scientific)</h4>
  
      <ul class="short">
      <li> Attended several Astrophysics summer/winter schools and conferences. </li>
      <li> <b>Teaching assistant </b> at an electrodynamics course and at several physics labs (<%= link_to "click here", additional_training_teaching_path%> for full list). </li>
      <li> Participated in various <b>student seminars</b> and attended graduate courses as a requirement of the <%= link_to 'IMPRS Heidelberg curriculum', 'http://www.mpia.de/imprs-hd/html/curriculum.html'%>.</li>
      <li> <b>Radio Astronomy internship</b> in the Radio Astronomy group of <%= link_to 'Prof. Denise Gabuzda', 'http://www.physics.ucc.ie/staff/dgabuzda.html'%> at the <%= link_to 'Department of Physics', 'http://physics.ucc.ie'%>, <%= link_to 'University College Cork', 'http://www.ucc.ie/en/'%> (2006).</li>
    </ul>
  </div>
 </div>
</div>

app/views/main/education.html.erb
<div class='box-i'>
  <h3>Education</h3>
  <table class='work'>
    <tr>
      <td class='cvleft'> July 2011</td>
      <td class='cvright'> Dr. Rer. Nat. Astrophysics, <%= link_to 'University of Heidelberg', 'http://www.uni-heidelberg.de/index_e.html'%>.  </td>
    </tr>
    <tr>
      <td class='cvleft'> Oct 2007 - Jul 2011 </td>
      <td class="cvright"> 
        <ul> 
          <li>Doctorate Student at the <%= link_to 'Max Planck Institute for Nuclear Physics (MPIK), Heidelberg', "http://www.mpi-hd.mpg.de/mpi/en/start/"%>.</li>
          <li><%= link_to 'IMPRS Heidelberg', 'http://www.mpia.de/imprs-hd/'%> fellow.</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td class='cvleft'> Oct 2005 - Sep 2007 </td>
      <td class='cvright'> Master Student at the <%= link_to 'Astrophysics Section', 'http://astro.phys.uoa.gr'%> of the <%= link_to 'Physics Faculty', 'http://phys.uoa.gr'%>, <%= link_to 'University of Athens', 'http://www.uoa.gr'%>.</td>
    </tr>
    <tr>
      <td class='cvleft bottom'> Sep 1999 - Sep 2005</td>
      <td class='cvright bottom'> Bachelor Student at the <%= link_to 'Astrophysics Section', 'http://astro.phys.uoa.gr'%> of the <%= link_to 'Physics Faculty', 'http://phys.uoa.gr'%>, specialization: Astrophysics. </td>
    </tr>
  </table>
</div>

app/views/main/engamovios.html.erb
<div class="box-i">
  <div>
	<h3> En Gamo Vios - Personal Blog</h3>
	
	<em> in Greek </em>
	   <p><%= link_to "En Gamo Vios(Εν Γάμω Βίος)", "http://engamovios.com"%> is my personal blog, in which I write about children, marriage, career, goals, life and anything that springs to mind. I sometimes host texts and pictures painted by my friend Christina. </p>
   	<p> There's also an extended recipe index. Enjoy! </p>	
   </div>
</div>

app/views/main/griechischekueche.html.erb
<div class="box-i">
	<h3> Griechische Küche</h3>
	
		<em> in German</em>
		<p>I'm an enthusiastic food blogger. I love cooking and presenting traditional greek dishes - and sometimes also my own creations - to the german food blogging community.</p>
    <p> I take pictures of my dishes using my old Nikon D40 camera with a Sigma 30mm f/1.4 lens. 		</p>
		<p> If you speak German and would like to try some greek recipes, you can visit <%= link_to "Griechische Küche", "http://griechischekueche.com"%>. There are lots of vegetarian and vegan dishes too!
		</p>
			<%= link_to image_tag("grk1.jpg"), "http://griechischekueche.com/2013/12/15/melomakarona/" %>
		
			 <%= link_to image_tag("grk2.jpg"), "http://griechischekueche.com/2015/01/10/zitroniges-ofenhahnchen-kotopulo-lemonato-sto-furno/" %>
		
			<%= link_to image_tag("grk3.jpg"), "http://griechischekueche.com/vegan/" %>
	<p class='right'><em> Click on the photos to get the recipes!</em> </p>

</div> <!--box-i-->

app/views/main/hobbies.html.erb
<div class="box-i contain">
  <div class='box-left'>
    <p>I enjoy cooking and baking. You can see my recipes in my blogs! I cook and bake from scratch, and I'm used to baking my own bread.</p>
  </div>
  
  <div class='box-right'>
    <p>I enjoy TV series, and some of my favourites are "How I met your mother", "House" and "NCIS".</p>
  </div>
	
	<div class='box-left'>
		<p>I like gardening and this year I'll try to grow as many vegetables as possible in my small garden.</p>
	</div>
	
</div>

app/views/main/impressum.html.erb
<div class="box-i">
	<h3> Impressum </h3>
	
	
	
	 Ioanna Arka <br />
	 conlance GmbH <br />
	 Werner-von-Siemens-Straße 6 <br />
	 Sigma Technopark Augsburg, Gebäude 9a <br />
	 D-86159 Augsburg <br />
	 E-Mail: <a href="mailto:ioanna.arka@conlance.de"> ioanna.arka@conlance.de </a> <br />
	
</div>

app/views/main/index.html.erb
	<div class="box-i">
		<%= image_tag "ioanna.jpg"%>
		<h3> Dr. Ioanna Arka </h3>
		<div class="short">
			 		<p> I'm a trainee web developer at <a href="http://conlance.de">conlance GmbH</a>. I'm learning Ruby on Rails, Javascript and other interesting stuff and I'm also developing a taste for web design. </p>     

			 		<p>I'm also a physicist holding a doctorate in Theoretical Astrophysics. I worked in Heidelberg, Germany and Grenoble, France before deciding to settle down with my family in a small town close to Munich.</p>
					<p>I'm an all-around mom of two lively and opinionated preschoolers.</p>
					<p>I'm also a passionate <a href="http://griechischekueche.com">cook and baker</a> and a dedicated <a href="http://lowcarbdeutschland.wordpress.com">food blogger</a>.</p>
			
				
		</div> 
	</div>
					

app/views/main/jobsforastronomers.html.erb
  <div class="box-i">
	
    <%= image_tag "JfA.jpg", class: "img-good" %>
  
	  <h3> The Jobs for Astronomers Initiative </h3>
	  <div class="short">
		
		
		  <p><a href="http://jobsforastronomers.com">Jobs for Astronomers</a> is an initiative, the purpose of which is to provide information on non-academic career paths for astronomers and astrophysicists. </p>
			<p> <a href="http://jobsforastronomers.com">Jobs for Astronomers</a> came to life in 2012 as a response to the lack of guidance and support that many astronomers and astrophysicists experience when deciding to switch career paths from academic to non-academic. </p> 
	
  	  <p>The dearth of permanent contracts and tenure-track positions in science, and the increasing number of PhD and post-doc positions, as well as the constant need of moving to find new jobs, make many researchers consider alternative career paths. <a href="http://jobsforastronomers.com">Jobs for Astronomers</a> is here to help researchers make a choice between different fields according to their experience and inclination. </p>
    </div>
	</div>

app/views/main/lowcarbdeutschland.html.erb
<div class="box-i">
	<h3> Low Carb Deutschland</h3>
	
		<em> in German </em>
		<p> In <%= link_to "Low Carb Deutschland", "http://lowcarbdeutschland.com"%> you can find tasty, healthy and easy low-carb recipes. Check it out!
		</p>
			
			<%= link_to image_tag("lcd1.jpg"), "http://lowcarbdeutschland.com/2014/11/17/spiegeleier-mit-tomaten-und-feta/" %>
		
			 <%= link_to image_tag("lcd2.jpg"), "http://lowcarbdeutschland.com/2014/07/23/3-minuten-mikrowellen-himbeer-cheesecake/" %>
		
			<%= link_to image_tag("lcd3.jpg"), "http://lowcarbdeutschland.com/2014/07/20/erfrischender-sommersalat/" %>
	<p class='right'><em> Click on the photos to get the recipes!</em> </p>
	
</div> <!--box-i-->

app/views/main/other_skills.html.erb
<div class='box-i'>
  <div class="short">
  
  <h4> Languages </h4>
    <ul class='short'>
      <li> Greek, Native proficiency. </li>
      <li> English, Professional working proficiency. </li>
      <li> German, Full professional proficiency. </li>
      <li> Swedish, Elementary proficiency. </li>
    </ul>  
  
  <h4> Additional Skills</h4>
  <ul class='short'>
  <li> <b> Public speaking</b>: talks and seminars given at several conferences, meetings and scientific institutes (<%=link_to 'click here', talks_seminars_path%> for full list). </li>
  <li> <b>Scientific writing</b>: author or co-author of several scientific articles (<%= link_to 'click here', "http://adsabs.harvard.edu/cgi-bin/nph-abs_connect?db_key=AST&db_key=PRE&qform=AST&arxiv_sel=astro-ph&arxiv_sel=cond-mat&arxiv_sel=cs&arxiv_sel=gr-qc&arxiv_sel=hep-ex&arxiv_sel=hep-lat&arxiv_sel=hep-ph&arxiv_sel=hep-th&arxiv_sel=math&arxiv_sel=math-ph&arxiv_sel=nlin&arxiv_sel=nucl-ex&arxiv_sel=nucl-th&arxiv_sel=physics&arxiv_sel=quant-ph&arxiv_sel=q-bio&sim_query=YES&ned_query=YES&adsobj_query=YES&aut_logic=OR&obj_logic=OR&author=Arka%2C+I.&object=&start_mon=&start_year=&end_mon=&end_year=&ttl_logic=OR&title=&txt_logic=OR&text=&nr_to_return=200&start_nr=1&jou_pick=ALL&ref_stems=&data_and=ALL&group_and=ALL&start_entry_day=&start_entry_mon=&start_entry_year=&end_entry_day=&end_entry_mon=&end_entry_year=&min_score=&sort=SCORE&data_type=SHORT&aut_syn=YES&ttl_syn=YES&txt_syn=YES&aut_wt=1.0&obj_wt=1.0&ttl_wt=0.3&txt_wt=3.0&aut_wgt=YES&obj_wgt=YES&ttl_wgt=YES&txt_wgt=YES&ttl_sco=YES&txt_sco=YES&version=1"%> for full list). </li>
</ul>
  </div>
</div>

app/views/main/teaching.html.erb
<div class='box-i'>
  <h3> Teaching Experience </h3>
    <table class='work'>
      <tr>
        <td class='cvleft'> 2009 - 2010</td>
        <td class='cvright'> Teaching Assistang in Electrodynamics Bachelor Course, <%= link_to 'University of Heidelberg', 'http://www.uni-heidelberg.de/index_e.html'%>.</td>
      </tr>
      <tr> 
        <td class='cvleft'> 2006 - 2007</td>
        <td class='cvright'> Teaching Assistant in Electrodynamics Labs, <%= link_to 'University of Athens', 'http://uoa.gr'%>.</td>
      </tr>
      <tr> 
        <td class='cvleft'> 2006 </td>
        <td class='cvright'>Teaching Assistant in Astronomy Labs, <%= link_to 'University of Athens', 'http://uoa.gr'%>. </td>
      </tr>
      <tr> 
        <td class='cvleft bottom'> 2006 </td>
        <td class='cvright bottom'> Teaching Assistant in Thermodynamics Labs, <%= link_to 'University of Athens', 'http://uoa.gr'%>.</td>
      </tr>
    </table>
</div>

app/views/main/work_experience.html.erb
<div class="box-i">
  <h3> Work Experience & Training </h3>
  <table class="work">
    <tr>
      <td class='cvleft'>  Dec 2014 - present </td>
      <td class='cvright'>  Trainee web developer at <%= link_to "conlance GmbH", "http://www.conlance.de" %>, Augsburg </td>
    </tr>
    <tr>
      <td class='cvleft bottom'>  Sep 2011 - Jan 2013 </td>
      <td class='cvright bottom'> Post-doctoral researcher at <%= link_to "Institut de Planétologie et d’Astrophysique de Grenoble", "http://ipag.osug.fr/?lang=en" %> </td>
    </tr>
  </table>
</div>